### ISSUE TITLE
Internationalized domain names do not work / Missing punycode conversion

### ISSUE THREAD

**Issue by haukepribnow** [shibayan/appservice-acmebot#156]
**Summary:** Trying to use appservice-acmebot with IDNs (internationalized domain names) fails.

**Example:** Let's use the following four hostnames as an example.
* example.de
* www.example.de
* example-ümlaut.de
* www.example-ümlaut.de

When trying to add a new certificate for the four hostnames, I get an error message like this:
```
Orchestrator function 'AddCertificate' failed:
The activity function 'Order' failed:
"Failed to deserialize exception from TaskActivity: {
"$type":"ACMESharp.Protocol.AcmeProtocolException, ACMESharp",
"ProblemType":16,
"ProblemTypeRaw":"urn:ietf:params:acme:error:rejectedIdentifier",
"ProblemDetail":"Error creating new order :: Cannot issue for \"example-ümlaut.de\": Domain name contains an invalid character (and 1 more problems. Refer to sub-problems for more information.)",
"ProblemStatus":400,
"StackTrace":"
   at ACMESharp.Protocol.AcmeProtocolClient.SendAcmeAsync(Uri uri, HttpMethod method, Object message, HttpStatusCode[] expectedStatuses, Boolean skipNonce, Boolean skipSigning, Boolean includePublicKey, CancellationToken cancel, String opName)
   at ACMESharp.Protocol.AcmeProtocolClient.CreateOrderAsync(IEnumerable`1 dnsIdentifiers, Nullable`1 notBefore, Nullable`1 notAfter, CancellationToken cancel)
   at AppService.Acmebot.SharedFunctions.Order(IList`1 hostNames) in d:\\a\\1\\s\\AppService.Acmebot\\SharedFunctions.cs:line 103
   at Microsoft.Azure.WebJobs.Host.Executors.FunctionInvoker`2.InvokeAsync(Object instance, Object[] arguments) in C:\\projects\\azure-webjobs-sdk-rqm4t\\src\\Microsoft.Azure.WebJobs.Host\\Executors\\FunctionInvoker.cs:line 52
   at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.InvokeAsync(IFunctionInvoker invoker, ParameterHelper parameterHelper, CancellationTokenSource timeoutTokenSource, CancellationTokenSource functionCancellationTokenSource, Boolean throwOnTimeout, TimeSpan timerInterval, IFunctionInstance instance) in C:\\projects\\azure-webjobs-sdk-rqm4t\\src\\Microsoft.Azure.WebJobs.Host\\Executors\\FunctionExecutor.cs:line 585
   at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.ExecuteWithWatchersAsync(IFunctionInstanceEx instance, ParameterHelper parameterHelper, ILogger logger, CancellationTokenSource functionCancellationTokenSource) in C:\\projects\\azure-webjobs-sdk-rqm4t\\src\\Microsoft.Azure.WebJobs.Host\\Executors\\FunctionExecutor.cs:line 532
   at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.ExecuteWithLoggingAsync(IFunctionInstanceEx instance, ParameterHelper parameterHelper, IFunctionOutputDefinition outputDefinition, ILogger logger, CancellationTokenSource functionCancellationTokenSource) in C:\\projects\\azure-webjobs-sdk-rqm4t\\src\\Microsoft.Azure.WebJobs.Host\\Executors\\FunctionExecutor.cs:line 468
   at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.ExecuteWithLoggingAsync(IFunctionInstanceEx instance, FunctionStartedMessage message, FunctionInstanceLogEntry instanceLogEntry, ParameterHelper parameterHelper, ILogger logger, CancellationToken cancellationToken) in C:\\projects\\azure-webjobs-sdk-rqm4t\\src\\Microsoft.Azure.WebJobs.Host\\Executors\\FunctionExecutor.cs:line 278",
"Message":"Error creating new order :: Cannot issue for \"example-ümlaut.de\": Domain name contains an invalid character (and 1 more problems. Refer to sub-problems for more information.)",
"Data":{"$type":"System.Collections.ListDictionaryInternal, System.Private.CoreLib"},
"InnerException":null,
"HelpLink":null,
"Source":"ACMESharp",
"HResult":-2146233088
}".
See the function execution logs for additional details.
```
(Added some linebreaks for readability.)

**Way towards a solution:** Add a conversion to Punycode before the request to Let's Encrypt is issued.

**Open question:** Where would be the "right" place for such a conversion (architecturally speaking)?

**Comment by shibayan** [comment]
Thank you for reporting the bug.

Originally I wanted to convert all Punycode, but since App Service has a host name in Unicode, I converted it to Punycode except around ARM API calls.

**Comment by haukepribnow** [comment]
Thanks so much for the incredibly fast reaction and fixing. It's working now.
