### ISSUE TITLE
CheckHttpChallenge fails for Windows based web app

### ISSUE THREAD

**Issue by abro1i** [shibayan/appservice-acmebot#188]
**Describe the bug**
Working fine for Linus but for a windows web app we get the following error:

> 2020-06-09T09:17:27Z   [Error]   Executed 'AddCertificate' (Failed, Id=88d140ae-a8b8-4294-b3c9-ccfb002932b3)
2020-06-09T09:17:27Z   [Error]   76f4c2b42bf44ecc97df38d5e54668ab: Function 'AddCertificate (Orchestrator)' failed with an error. Reason: Microsoft.Azure.WebJobs.Extensions.DurableTask.FunctionFailedException: The orchestrator function 'IssueCertificate' failed: "The activity function 'CheckHttpChallenge' failed: "Exception of type 'System.Net.Http.HttpRequestException' was thrown.". See the function execution logs for additional details.". See the function execution logs for additional details.
 ---> Microsoft.Azure.WebJobs.Extensions.DurableTask.FunctionFailedException: The activity function 'CheckHttpChallenge' failed: "Exception of type 'System.Net.Http.HttpRequestException' was thrown.". See the function execution logs for additional details.
 ---> System.Net.Http.HttpRequestException: Exception of type 'System.Net.Http.HttpRequestException' was thrown.
   --- End of inner exception stack trace ---
   at Microsoft.Azure.WebJobs.Extensions.DurableTask.DurableOrchestrationContext.CallDurableTaskFunctionAsync[TResult](String functionName, FunctionType functionType, Boolean oneWay, String instanceId, String operation, RetryOptions retryOptions, Object input, Nullable`1 scheduledTimeUtc) in d:\a\r1\a\azure-functions-durable-extension\src\WebJobs.Extensions.DurableTask\ContextImplementations\DurableOrchestrationContext.cs:line 632
   at AppService.Acmebot.SharedFunctions.IssueCertificate(IDurableOrchestrationContext context, ILogger log) in C:\gitroot\cuisines-acmebotssl-pipm-dotnet\AppService.Acmebot\SharedFunctions.cs:line 106
   at Microsoft.Azure.WebJobs.Host.Executors.FunctionInvoker`2.InvokeAsync(Object instance, Object[] arguments) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionInvoker.cs:line 52
   at Microsoft.Azure.WebJobs.Extensions.DurableTask.TaskOrchestrationShim.Execute(OrchestrationContext innerContext, String serializedInput) in d:\a\r1\a\azure-functions-durable-extension\src\WebJobs.Extensions.DurableTask\Listener\TaskOrchestrationShim.cs:line 96
   --- End of inner exception stack trace ---
   at Microsoft.Azure.WebJobs.Extensions.DurableTask.DurableOrchestrationContext.CallDurableTaskFunctionAsync[TResult](String functionName, FunctionType functionType, Boolean oneWay, String instanceId, String operation, RetryOptions retryOptions, Object input, Nullable`1 scheduledTimeUtc) in d:\a\r1\a\azure-functions-durable-extension\src\WebJobs.Extensions.DurableTask\ContextImplementations\DurableOrchestrationContext.cs:line 642
   at AppService.Acmebot.AddCertificateFunctions.AddCertificate(IDurableOrchestrationContext context, ILogger log) in C:\gitroot\cuisines-acmebotssl-pipm-dotnet\AppService.Acmebot\AddCertificateFunctions.cs:line 61
   at Microsoft.Azure.WebJobs.Host.Executors.VoidTaskMethodInvoker`2.InvokeAsync(TReflected instance, Object[] arguments) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\VoidTaskMethodInvoker.cs:line 20
   at Microsoft.Azure.WebJobs.Host.Executors.FunctionInvoker`2.InvokeAsync(Object instance, Object[] arguments) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionInvoker.cs:line 52
   at Microsoft.Azure.WebJobs.Extensions.DurableTask.TaskOrchestrationShim.Execute(OrchestrationContext innerContext, String serializedInput) in d:\a\r1\a\azure-functions-durable-extension\src\WebJobs.Extensions.DurableTask\Listener\TaskOrchestrationShim.cs:line 96. IsReplay: False. State: Failed. HubName: DurableFunctionsHub. AppName: acmebotssl-pipm. SlotName: Production. ExtensionVersion: 2.2.1. SequenceNumber: 20.

Any idea what might be wrong?

Thanks and keep up the good work!

**Comment by shibayan** [comment]
It looks like you are failing to resolve the hostname, so make sure you can access that host in your browser first.
I can't advise you any further as it doesn't appear to be the recommended deployment method.

**Comment by skulawik** [comment]
Thanks, solved it by creating the CNAME entry beforehand. However actually we do have still a problem with the Windows App Service recycling a used domain entry from a previous Linux App Service.
For the Linux App Service I understand, the TXT Entry will authenticate against Lets Encrypt. On Windows the .well-known/ path is to let Lets Encrypt verify authenticity. 
After adding a "random" domain to the Windows App Service the .well-known path has been created and the acme-challenge created. When recycling one of the other DNS entries, neither the acme-challenge has been updated nor we get it to work - currently the error message is:

`Orchestrator function 'AddCertificate' failed: The orchestrator function 'IssueCertificate' failed: "The activity function 'Http01Authorization' failed: "Sequence contains no matching element". See the function execution logs for additional details.". See the function execution logs for additional details.`

Unfortunately tracing is quite hard as we miss detailed descriptions in the log:

`2020-06-10 06:24:19.151
Executing 'Http01Authorization' (Reason='', Id=a3410a8e-b737-4d73-a5e9-edc260302432)
Information
2020-06-10 06:24:19.914
Sequence contains no matching element
Error
2020-06-10 06:24:19.914
Executed 'Http01Authorization' (Failed, Id=a3410a8e-b737-4d73-a5e9-edc260302432)
Error
2020-06-10 06:24:19.917
Sequence contains no matching element
Error`

**Comment by shibayan** [comment]
Do you want to use a domain used to Windows from Linux App Service? This is an error that is not intended to occur, and occurs only when http-01 is not available.

**Comment by skulawik** [comment]
No, we had used the acmebot previously to create a SSL cert for the Linux App Service (for a Website). However we wanted to switch to Windows because of Performance and Application Insights and so I disabled the Linux App Service and was trying to assign the same domain to the new Windows App Service. Then this error occurs (even if i disable the old Linux App Service)

**Comment by shibayan** [comment]
This error is a result of the Let's Encrypt side authenticating once with DNS-01. This is due to the fact that HTTP-01 is disabled. I'll look into how to deal with it, but the only workaround might be to recreate your account.

**Comment by skulawik** [comment]
ok why not. However if I choose a test45345.someotherdomain.com for example it will go through - is this a "different account" or why is this working then?

**Comment by skulawik** [comment]
@shibayan Why are you not using DNS01 Challenge also for Windows services as you do for Linux services?

**Comment by shibayan** [comment]
This seems to be a constraint that only occurs for domains that have already been published.
For those cases, a Key Vault version is available, which makes it easy to use the HTTP-01. This depends on the design philosophy.

**Comment by shibayan** [comment]
If you want to continue the conversation any further, put up another issue because it's a completely different issue.

**Comment by skulawik** [comment]
@shibayan moved the issue to https://github.com/shibayan/appservice-acmebot/issues/189 as by your request

**Comment by shibayan** [comment]
The recent update should have improved it.
