### ISSUE TITLE
Browsing function "api/add-certificate" returns Function host is not running.

### ISSUE THREAD

**Issue by valeriob** [shibayan/appservice-acmebot#201]
**Describe the bug**
Browsing function "api/add-certificate" returns Function host is not running.

**Additional context**
I installed the bot one year ago and about may 2020 it stopped updating certificates. One of the certificates expired the 27/7/2020 and today i tried to renew it manually hitting the address add-certificate but i got the error.

This is the host log : 

2020-07-28T02:44:44.618 [Information] Starting JobHost
2020-07-28T02:44:44.620 [Information] Starting Host (HostId=xxx, InstanceId=a9168a9e-7824-4113-b35a-778b7cecf2d5, Version=2.0.13900.0, ProcessId=6416, AppDomainId=1, InDebugMode=True, InDiagnosticMode=False, FunctionsExtensionVersion=~2)
2020-07-28T02:44:44.726 [Information] Loading functions metadata
2020-07-28T02:44:44.729 [Information] Loading proxies metadata
2020-07-28T02:44:44.735 [Information] Initializing Azure Function proxies
2020-07-28T02:44:48.258 [Information] 1 proxies loaded
2020-07-28T02:44:48.741 [Error] A host error has occurred during startup operation '36a4d932-2395-488e-93e1-a9a3062c8101'.
System.InvalidOperationException : Found duplicate FunctionMetadata with the name AddCertificate
   at Microsoft.Azure.WebJobs.Script.FunctionMetadataManager.AddMetadataFromCustomProviders(List`1 functionMetadataList) at D:\a\1\s\src\WebJobs.Script\Host\FunctionMetadataManager.cs : 193
   at Microsoft.Azure.WebJobs.Script.FunctionMetadataManager.LoadFunctionMetadata(Boolean forceRefresh) at D:\a\1\s\src\WebJobs.Script\Host\FunctionMetadataManager.cs : 123
   at Microsoft.Azure.WebJobs.Script.FunctionMetadataManager.GetFunctionMetadata(Boolean forceRefresh,Boolean applyWhitelist) at D:\a\1\s\src\WebJobs.Script\Host\FunctionMetadataManager.cs : 68
   at Microsoft.Azure.WebJobs.Script.ScriptHost.GetFunctionsMetadata() at D:\a\1\s\src\WebJobs.Script\Host\ScriptHost.cs : 340
   at async Microsoft.Azure.WebJobs.Script.ScriptHost.InitializeAsync(CancellationToken cancellationToken) at D:\a\1\s\src\WebJobs.Script\Host\ScriptHost.cs : 274
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.Azure.WebJobs.Script.ScriptHost.StartAsyncCore(CancellationToken cancellationToken) at D:\a\1\s\src\WebJobs.Script\Host\ScriptHost.cs : 251
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.Extensions.Hosting.Internal.Host.StartAsync(CancellationToken cancellationToken)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.Azure.WebJobs.Script.WebHost.WebJobsScriptHostService.UnsynchronizedStartHostAsync(ScriptHostStartupOperation activeOperation,Int32 attemptCount,JobHostStartupMode startupMode) at D:\a\1\s\src\WebJobs.Script.WebHost\WebJobsScriptHostService.cs : 266
2020-07-28T02:44:48.836 [Information] Stopping JobHost
2020-07-28T02:44:49.881 [Information] Loading functions metadata

**Comment by shibayan** [comment]
This seems to be caused by using Acmebot v2, which is no longer supported. Please follow #138 to upgrade to v3.

**Comment by valeriob** [comment]
I will, thanks.

**Comment by valeriob** [comment]
Just a followup question,
after the upgrade i get the error : 

_Orchestrator function 'AddCertificate' failed: The orchestrator function 'IssueCertificate' failed: "The activity function 'Dns01Precondition' failed: "Azure DNS zone "mysite.domain.com" is not found". See the function execution logs for additional details.". See the function execution logs for additional details._

In the documentation i read that 
_To issue certificates for "App Service on Linux" and "Web App for Container", Azure DNS is always required._
Does this mean that it now uses the DNS-01 challenge instead of the HTTP-01 challenge ? Is it possible to switch to HTTP challenge and use another dns provider ?

Thanks

**Comment by shibayan** [comment]
>Does this mean that it now uses the DNS-01 challenge instead of the HTTP-01 challenge ? Is it possible to switch to HTTP challenge and use another dns provider ?

Yes, because HTTP-01 is not available in Linux / Web App for Container, i.e. DNS-01 is required.
If it is for the Windows App Service, it should automatically use HTTP-01. The exception is wildcard certificates.

**Comment by valeriob** [comment]
Thanks @shibayan 
Is this change due to the new v3 protocol ? Or some security issue ?

**Comment by shibayan** [comment]
No, HTTP-01 has not been running on Linux since the beginning. v2 and v3 differ in terms of the version of the Azure Function Runtime. HTTP-01 uses Windows App Service-dependent features, so it will never work outside of Windows.

**Comment by valeriob** [comment]
Thanks for the explanation !
